### ISSUE TITLE
click_log only applies to the initial module's logger.

### ISSUE THREAD

**Issue by WhyNotHugo** [click-contrib/click-log#9]
On an app with more than one logger, click_log will configure the logger for the initial module (where `click_log.basic_config` is called), but not other modules.

This results in `click_log` effectively having no effect on other modules.

A potential solution for this, would be to make `basic_config` take `logger` as an OPTIONAL parameter.
If `logger == None`, then configure `logging` (which basically means, override global defaults).

**Comment by untitaker** [comment]
>click_log will configure the logger for the initial module (where click_log.basic_config is called), but not other modules.

`basic_config` takes a logger and configures it. If you call it with `__name__` it will only configure the logger for the CLI module. Call it with `"todoman"`.

**Comment by WhyNotHugo** [comment]
That still won't activate logging for third party libraries though (which is in many cases desirable).

**Comment by untitaker** [comment]
Then pass the root logger instead

On 29 August 2017 18:21:54 GMT+02:00, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>That still won't activate logging for third party libraries though
>(which is in many cases desirable).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/click-contrib/click-log/issues/9#issuecomment-325717434

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by simonvanderveldt** [comment]
> Then pass the root logger instead

I had to do this for both `click_log.basic_config("")` as well as `@click_log.simple_verbosity_option("")`.
I'm not sure this makes sense?

With the previous version none of this was necessary btw, which was the behaviour I was expecting. I'd prefer it to work the way it did, i.e. the logger is configured for all loggers.
If it's going to stay the way it is right now this should probably be documented, I'd expect more people to start asking this question.

**Comment by untitaker** [comment]
On Thu, Sep 14, 2017 at 08:44:23AM +0000, Simon van der Veldt wrote:
> > Then pass the root logger instead
> I had to do this for both `click_log.basic_config("")` as well as `@click_log.simple_verbosity_option("")`. I'm not sure this makes sense?

This does make sense, since that is the root logger. Same as
`basic_config(logging.getLogger())` or `basic_config()`.

> 
> With the previous version none of this was necessary btw, which was the behaviour I was expecting. I'd prefer it to work the way it did, i.e. the logger is configured for all loggers.

The behavior didn't change in that regard. You still pass a logger to
basic_config / init, the default is the root logger.

> If it's going to stay the way it is right now this should be documented.

Sure, which part of the docs are you referring to?

**Comment by simonvanderveldt** [comment]
> The behavior didn't change in that regard. You still pass a logger to
> basic_config / init, the default is the root logger.

This is not the case for `simple_verbosity_option` since it doesn't come with a default assigned to `logger`, see https://github.com/click-contrib/click-log/blob/64c618879b8192aa2d9852476a506e5588e1ca14/click_log/options.py#L7

> Sure, which part of the docs are you referring to?

Something like adding a title/header with contents for:
- "Controlling the verbosity of your click-log using module". (Don't use this exact wording, it sucks :P)
- "Controlling the verbosity of all modules used"
